Repository CotripperPlatform/CoTrip, pull requests merged in 2019-12, with the labels that each got.

#133 Component: Post Body PR
  client/src/components/PostBody/PostBody.css
  client/src/components/PostBody/PostBody.js
  client/src/components/PostBody/PostBody.stories.js
  client/src/components/PostBody/PostBody.test.js
Labels: Atomic Component

#116 Component: Input Text Field PR
  client/src/components/InputTextField/InputTextField.css
  client/src/components/InputTextField/InputTextField.js
  client/src/components/InputTextField/InputTextField.stories.js
  client/src/components/InputTextField/InputTextField.test.js
Labels: Atomic Component

#128 Component: Comment Body PR
  client/src/components/CommentBody/CommentBody.css
  client/src/components/CommentBody/CommentBody.js
  client/src/components/CommentBody/CommentBody.stories.js
  client/src/components/CommentBody/CommentBody.test.js
Labels: Atomic Component

#115 Component: Button PR
  client/src/App.css
  client/src/components/Button/Button.css
  client/src/components/Button/Button.js
  client/src/components/Button/Button.stories.js
  client/src/components/Button/Button.test.js
Labels: atomic component

#157 Component: InfoCard Base PR
  client/src/App.css
  client/src/components/Card/Card.css
  client/src/components/Card/Card.js
  client/src/components/Card/Card.stories.js
  client/src/components/Card/Card.test.js
Labels: atomic component

#152 Profile Picture Component #24
  client/src/components/ProfilePicture/ProfilePicture.css
  client/src/components/ProfilePicture/ProfilePicture.js
  client/src/components/ProfilePicture/ProfilePicture.stories.js
  client/src/components/ProfilePicture/ProfilePicture.test.js
Labels: atomic component

#185 fixed css of medium type and now all four types are rendering correctly
  client/src/components/ProfilePicture/ProfilePicture.css
Labels: atomic component

#177 Component: Trending Hashtag Card
  client/src/components/TrendingHashtagCard/TrendingHashtagCard.css
  client/src/components/TrendingHashtagCard/TrendingHashtagCard.js
  client/src/components/TrendingHashtagCard/TrendingHashtagCard.stories.js
  client/src/components/TrendingHashtagCard/TrendingHashtagCard.test.js
Labels: molecular component

#132 Component: media image card
  assets/images/card_medium1.png
  assets/images/media-card-1.png
  assets/images/media-card-2.png
  assets/images/media-card-3.png
  assets/images/media-card-4.png
  assets/images/media-card-5.png
  assets/images/media-card-6.png
  client/src/components/MediaCard/MediaCard.css
  client/src/components/MediaCard/MediaCard.js
  client/src/components/MediaCard/MediaCard.stories.js
  client/src/components/MediaCard/MediaCard.test.js
Labels: atomic component

#180 Component: Upcoming Events Card PR
  client/src/components/UpcomingEventsCard/UpcomingEventsCard.css
  client/src/components/UpcomingEventsCard/UpcomingEventsCard.js
  client/src/components/UpcomingEventsCard/UpcomingEventsCard.stories.js
  client/src/components/UpcomingEventsCard/UpcomingEventsCard.test.js
Labels: atomic component

#187 Component: Card PR
  client/src/components/Card/Card.css
  client/src/components/Card/Card.js
Labels: atomic component

#169 Burger component PR
  client/src/components/Burger/Burger.css
  client/src/components/Burger/Burger.js
  client/src/components/Burger/Burger.stories.js
  client/src/components/Burger/Burger.test.js
  client/src/components/Navbar/Navbar.css
  client/src/components/Navbar/Navbar.js
  client/src/components/Navbar/Navbar.stories.js
  client/src/components/Navbar/Navbar.test.js
Labels: atomic component

#124 Component: Input Type Select PR
  client/src/components/InputSelect/InputSelect.css
  client/src/components/InputSelect/InputSelect.js
  client/src/components/InputSelect/InputSelect.stories.js
  client/src/components/InputSelect/InputSelect.test.js
Labels: atomic component

#113 #68 PillSelect Component complete and ready for review PR
  client/src/components/Pill/Pill.css
  client/src/components/Pill/Pill.js
  client/src/components/Pill/Pill.stories.js
  client/src/components/Pill/Pill.test.js
  client/src/components/Pill/heart-pink.svg
  client/src/components/Pill/heart-red.svg
  client/src/components/Pill/heart-white.svg
Labels: atomic component

#189 Component: Trending hashtag card, quick change, PR
  client/src/components/TrendingHashtagCard/TrendingHashtagCard.css
  client/src/components/TrendingHashtagCard/TrendingHashtagCard.js
Labels: molecular component

#111 #84 CarouselDots component completed PR
  client/src/components/CarouselDots/CarouselDots.css
  client/src/components/CarouselDots/CarouselDots.js
  client/src/components/CarouselDots/CarouselDots.stories.js
  client/src/components/CarouselDots/CarouselDots.test.js
Labels: atomic component

#114 Footer component PR
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.js
  client/src/components/Footer/Footer.stories.js
  client/src/components/Footer/Footer.test.js
Labels: stand alone

#198 Component: Card PR
  client/src/components/Card/Card.css
  client/src/components/Card/Card.stories.js
Labels: atomic component

#143 completed atomic nav bar link components
  client/src/App.css
  client/src/components/NavLink/NavLink.css
  client/src/components/NavLink/NavLink.js
  client/src/components/NavLink/NavLink.stories.js
  client/src/components/NavLink/NavLink.test.js
  client/src/components/NavLinkDropdownMenu/NavLinkDropdownMenu.css
  client/src/components/NavLinkDropdownMenu/NavLinkDropdownMenu.js
  client/src/components/NavLinkDropdownMenu/NavLinkDropdownMenu.stories.js
  client/src/components/NavLinkDropdownMenu/NavLinkDropdownMenu.test.js
Labels: atomic component

#156 Component: Group Card PR
  client/src/components/GroupCard/GroupCard.css
  client/src/components/GroupCard/GroupCard.js
  client/src/components/GroupCard/GroupCard.stories.js
  client/src/components/GroupCard/GroupCard.test.js
Labels: atomic component

#205 consolidated sizes into one story
  client/src/components/MediaCard/MediaCard.stories.js
Labels: atomic component

#209 Component: Input text field, PR plz pull me fast
  client/src/components/InputTextField/InputTextField.css
Labels: atomic component, bug

#260 Fixed changed color of burger to white per mock. Also rounded corners. PR
  client/src/components/Burger/Burger.css
Labels: atomic component

#129 Component: TripCard PR
  client/src/components/TripCard/TripCard.css
  client/src/components/TripCard/TripCard.js
  client/src/components/TripCard/TripCard.stories.js
  client/src/components/TripCard/TripCard.test.js
Labels: atomic component

#203 PR: Component extra users
  client/src/components/ExtraUsers/ExtraUsers.css
  client/src/components/ExtraUsers/ExtraUsers.js
  client/src/components/ExtraUsers/ExtraUsers.stories.js
  client/src/components/ExtraUsers/ExtraUsers.test.js
Labels: atomic component

#186 component: Interactioncard PR
  client/src/components/InteractionCard/InteractionCard.css
  client/src/components/InteractionCard/InteractionCard.js
  client/src/components/InteractionCard/InteractionCard.stories.js
  client/src/components/InteractionCard/InteractionCard.test.js
  package-lock.json
Labels: molecular component

#275 Component: Group Card Responsiveness PR
  client/src/components/GroupCard/GroupCard.css
Labels: bug, responsive

#276 Component: Upcoming Events Card Responsiveness PR
  client/src/components/UpcomingEventsCard/UpcomingEventsCard.css
Labels: bug, responsive

#182 Component: Previous Trip Card
  client/src/components/Card/Card.css
  client/src/components/PreviousTripsCard/PreviousTripsCard.css
  client/src/components/PreviousTripsCard/PreviousTripsCard.js
  client/src/components/PreviousTripsCard/PreviousTripsCard.stories.js
  client/src/components/PreviousTripsCard/PreviousTripsCard.test.js
Labels: molecular component

#249 responsive splash page
  client/src/App.css
  client/src/App.js
  client/src/assets/images/splash_background_mobile.png
  client/src/components/NavLinkDropdownMenu/NavLinkDropdownMenu.js
  client/src/components/SplashPage/SplashPage.css
  client/src/components/SplashPage/SplashPage.js
  client/src/index.css
  client/src/pages/SplashPage/SplashPage.css
  client/src/pages/SplashPage/SplashPage.js
  client/src/pages/SplashPage/SplashPage.stories.js
  client/src/pages/SplashPage/SplashPage.test.js
Labels: molecular component, responsive

#297 Logo Test Pull Request
  client/src/components/Logo/Logo.test.js
Labels: unit testing

#293 Added size prop so that modifier can be used PR
  client/src/components/Icon/Icon.js
Labels: atomic component

#126 Component: Molecular Upcoming Trips Card PR
  client/src/components/UpcomingTripsCard/UpcomingTripsCard.css
  client/src/components/UpcomingTripsCard/UpcomingTripsCard.js
  client/src/components/UpcomingTripsCard/UpcomingTripsCard.stories.js
  client/src/components/UpcomingTripsCard/UpcomingTripsCard.test.js
  package-lock.json
Labels: molecular component

#280 Bookatripcard PR
  client/src/assets/images/Hawaii-resort.jpg
  client/src/components/BookTripCard/BookTripCard.css
  client/src/components/BookTripCard/BookTripCard.js
  client/src/components/BookTripCard/BookTripCard.stories.js
  client/src/components/BookTripCard/BookTripCard.test.js
Labels: molecular component

#320 ForumPost Component PR
  client/src/components/ForumPost/ForumPost.test.js
Labels: unit testing

#319 Extra Users Component PR
  client/src/components/ExtraUsers/ExtraUsers.test.js
Labels: unit testing

#318 Previous Trip Card Test PR
  client/src/components/PreviousTripsCard/PreviousTripsCard.js
  client/src/components/PreviousTripsCard/PreviousTripsCard.test.js
Labels: unit testing

#317 TripDetails Test PR
  client/src/components/TripDetails/TripDetails.test.js
Labels: unit testing

#316 TripCard Tests PR
  client/src/components/TripCard/TripCard.test.js
Labels: unit testing

#309 Navlink Test PR
  client/src/components/NavLink/NavLink.js
  client/src/components/NavLink/NavLink.test.js
Labels: unit testing

#308 Comment Body Test PR
  client/src/components/CommentBody/CommentBody.js
  client/src/components/CommentBody/CommentBody.test.js
Labels: unit testing

#307 MediaCard Test PR
  client/src/components/MediaCard/MediaCard.test.js
Labels: unit testing

#306 InputTextField Test PR
  client/src/components/InputTextField/InputTextField.js
  client/src/components/InputTextField/InputTextField.test.js
Labels: unit testing

#305 Footer Test PR
  client/src/components/Footer/Footer.test.js
Labels: unit testing

#327 add auth tokens PR
  .vscode/settings.json
  api/Pipfile
  api/Pipfile.lock
  api/accounts/api.py
  api/accounts/migrations/0003_auto_20191216_1459.py
  api/accounts/models.py
  api/accounts/serializers.py
  api/accounts/urls.py
  api/api/settings.py
Labels: backend

#337 hotfix
  client/src/components/BookTripCard/BookTripCard.css
Labels: bug

#344 Book Trip Test PR
  client/src/components/BookTripCard/BookTripCard.test.js
Labels: unit testing

#328 Trending Hashtag Test PR
  client/src/components/TrendingHashtagCard/TrendingHashtagCard.js
  client/src/components/TrendingHashtagCard/TrendingHashtagCard.test.js
Labels: unit testing

#325 Component: Card, (added mobile cards) PR
  assets/images/add-friend.png
  assets/images/airplane-shape.png
  assets/images/google-trends (2).png
  assets/images/protest.png
  client/src/assets/images/add-friend.png
  client/src/assets/images/airplane-shape.png
  client/src/assets/images/protest.png
  client/src/assets/images/trending-hashtags.png
  client/src/components/Card/Card.css
  client/src/components/Card/Card.js
  client/src/components/Card/Card.stories.js
Labels: atomic component

#346 Component: Book A Trip Page Image PR
  client/src/components/BookATripImage/BookATripImage.css
  client/src/components/BookATripImage/BookATripImage.js
  client/src/components/BookATripImage/BookATripImage.stories.js
  client/src/components/BookATripImage/BookATripImage.test.js
Labels: atomic component

#348 Fixed Receivers
  api/accounts/serializers.py
  api/accounts/signals.py
Labels: backend

#206 Jest and Enzyme Tests PR
  .gitignore
  client/.storybook/config.js
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.test.js
  client/src/__snapshots__/App.test.js.snap
  client/src/__snapshots__/storybook.test.js.snap
  client/src/components/BookTripCard/BookTripCard.js
  client/src/components/BookTripCard/BookTripCard.test.js
  client/src/components/Burger/Burger.test.js
  client/src/components/Button/Button.test.js
  client/src/components/Card/Card.js
  client/src/components/Card/Card.test.js
  client/src/components/CarouselDots/CarouselDots.js
  client/src/components/CarouselDots/CarouselDots.test.js
  client/src/components/CommentBody/CommentBody.js
  client/src/components/CommentBody/CommentBody.test.js
  client/src/components/ExtraUsers/ExtraUsers.test.js
  client/src/components/Footer/Footer.test.js
  client/src/components/ForumPost/ForumPost.test.js
  client/src/components/Icon/Icon.test.js
  client/src/components/InputSelect/InputSelect.js
  client/src/components/InputSelect/InputSelect.test.js
  client/src/components/InputTextField/InputTextField.js
  client/src/components/InputTextField/InputTextField.test.js
  client/src/components/Logo/Logo.test.js
  client/src/components/MediaCard/MediaCard.test.js
  client/src/components/NavLink/NavLink.js
  client/src/components/NavLink/NavLink.test.js
  client/src/components/NavLinkDropdownMenu/NavLinkDropdownMenu.js
  client/src/components/NavLinkDropdownMenu/NavLinkDropdownMenu.stories.js
  client/src/components/NavLinkDropdownMenu/NavLinkDropdownMenu.test.js
  client/src/components/PostBody/PostBody.test.js
  client/src/components/PreviousTripsCard/PreviousTripsCard.js
  client/src/components/PreviousTripsCard/PreviousTripsCard.test.js
  client/src/components/ProfilePicture/ProfilePicture.test.js
  client/src/components/TrendingHashtagCard/TrendingHashtagCard.js
  client/src/components/TrendingHashtagCard/TrendingHashtagCard.test.js
  client/src/components/TripCard/TripCard.test.js
  client/src/components/TripDetails/TripDetails.test.js
  client/src/components/UpcomingEventsCard/UpcomingEventsCard.js
  client/src/components/UpcomingEventsCard/UpcomingEventsCard.test.js
  client/src/components/UpcomingTripsCard/UpcomingTripsCard.js
  client/src/components/UpcomingTripsCard/UpcomingTripsCard.test.js
  client/src/pages/SplashPage/SplashPage.js
  client/src/pages/SplashPage/SplashPage.test.js
  client/src/setupTests.js
  utils/utils.js
Labels: unit testing

#334 User Auth Tokens and Profile Model PR
  .vscode/settings.json
  api/Pipfile
  api/Pipfile.lock
  api/accounts/__init__.py
  api/accounts/admin.py
  api/accounts/api.py
  api/accounts/apps.py
  api/accounts/managers.py
  api/accounts/migrations/0001_initial.py
  api/accounts/migrations/__init__.py
  api/accounts/models.py
  api/accounts/serializers.py
  api/accounts/tests.py
  api/accounts/urls.py
  api/accounts/views.py
  api/api/settings.py
  api/api/urls.py
  api/cotrip_app/migrations/0001_initial.py
  api/cotrip_app/models.py
  api/cotrip_app/urls.py
Labels: backend

#278 Add accounts app, user signup and login PR
  api/Pipfile
  api/Pipfile.lock
  api/accounts/__init__.py
  api/accounts/admin.py
  api/accounts/apps.py
  api/accounts/migrations/__init__.py
  api/accounts/models.py
  api/accounts/serializers.py
  api/accounts/tests.py
  api/accounts/urls.py
  api/accounts/views.py
  api/api/settings.py
  api/api/urls.py
Labels: backend

#248 component: Signnupad PR
  client/src/components/SignUpAd/SignUpAd.css
  client/src/components/SignUpAd/SignUpAd.js
  client/src/components/SignUpAd/SignUpAd.stories.js
  client/src/components/SignUpAd/SignUpAd.test.js
Labels: molecular component

#354 Component: Input Text Field, PR
  client/src/components/InputTextField/InputTextField.css
Labels: atomic component

#358 added cors to backend
  api/Pipfile
  api/Pipfile.lock
  api/api/settings.py
Labels: backend

#162 Component Banner PR
  client/package-lock.json
  client/package.json
  client/src/components/Banner/Banner.css
  client/src/components/Banner/Banner.js
  client/src/components/Banner/Banner.stories.js
  client/src/components/Banner/Banner.test.js
  client/src/components/Banner/Banner__pink.png
  client/src/components/Banner/Banner__purple--big.png
  client/src/components/Banner/Banner__purple--small.png
Labels: atomic component

#165 Person Card (New Individual Mom Box)
  client/src/components/Assets/Images/Mom.png
  client/src/components/CommentBody/CommentBody.stories.js
  client/src/components/InputTextField/InputTextField.stories.js
  client/src/components/Logo/Logo.css
  client/src/components/Logo/Logo.js
  client/src/components/Logo/Logo.stories.js
  client/src/components/PersonCard/PersonCard.css
  client/src/components/PersonCard/PersonCard.js
  client/src/components/PersonCard/PersonCard.stories.js
  client/src/components/PersonCard/PersonCard.test.js
  client/src/components/PostBody/PostBody.stories.js
  client/src/components/PostBody/PostBody.test.js
Labels: molecular component

#357 Component: Group Card Bug PR
  client/package-lock.json
  client/src/components/BookATripImage/BookATripImage.css
  client/src/components/GroupCard/GroupCard.css
  client/src/components/GroupCard/GroupCard.js
  client/src/components/GroupCard/GroupCard.stories.js
Labels: atomic component, bug

#359 Added Cors and Topics to Profile PR
  api/Pipfile
  api/Pipfile.lock
  api/accounts/migrations/0002_profile_topics.py
  api/accounts/models.py
  api/api/settings.py
Labels: backend

#363 add larger logo for login page PR
  client/src/components/Logo/Logo.css
  client/src/components/Logo/Logo.js
  client/src/components/Logo/Logo.stories.js
Labels: atomic component

#366 Logo link hot fix
  client/src/components/Logo/Logo.js
Labels: atomic component

#361 Component/Page: Coming Soon PR
  client/src/App.js
  client/src/pages/ComingSoonPage/ComingSoonPage.css
  client/src/pages/ComingSoonPage/ComingSoonPage.js
  client/src/pages/ComingSoonPage/ComingSoonPage.stories.js
  client/src/pages/ComingSoonPage/ComingSoonPage.test.js
Labels: atomic component

#362 Component: Book A Trip Page Images PR
  client/src/components/Banner/Banner.stories.js
  client/src/components/BookATripImage/BookATripImage.css
  client/src/components/BookATripImage/BookATripImage.js
  client/src/components/BookATripImage/BookATripImage.stories.js
  client/src/components/BookATripImage/BookATripImage.test.js
Labels: atomic component, bug

#295 Forum Comment
  client/src/components/Assets/Images/Mom.png
  client/src/components/ForumComment/ForumComment.css
  client/src/components/ForumComment/ForumComment.js
  client/src/components/ForumComment/ForumComment.stories.js
  client/src/components/ForumComment/ForumComment.test.js
Labels: molecular component

#119 Component: ActivityList
  client/package-lock.json
  client/src/components/ActivityList/ActivityList.css
  client/src/components/ActivityList/ActivityList.js
  client/src/components/ActivityList/ActivityList.stories.js
  client/src/components/ActivityList/ActivityList.test.js
  client/src/components/Card/Card.css
Labels: molecular component

#370 Component groups list
  client/src/assets/images/card-image-2.png
  client/src/assets/images/card-image.png
  client/src/components/GroupsList/GroupsList.css
  client/src/components/GroupsList/GroupsList.js
  client/src/components/GroupsList/GroupsList.stories.js
  client/src/components/GroupsList/GroupsList.test.js
Labels: molecular component

#376 Added in documentation for changing sizes of icons PR
  client/README.md
Labels: documentation

#284 Navbar molecular component PR
  client/src/components/Navbar/Navbar.css
  client/src/components/Navbar/Navbar.js
  client/src/components/Navbar/Navbar.stories.js
Labels: molecular component

#386 Adjusting css to remove z-index for now since it's not behaving properly - Hofix
  client/src/components/Navbar/Navbar.css
Labels: bug

#381 Responsive Changes, Card PR
  client/src/App.js
  client/src/components/BookTripCard/BookTripCard.css
  client/src/components/BookTripCard/BookTripCard.js
  client/src/components/BookTripCard/BookTripCard.stories.js
  client/src/components/Card/Card.css
  client/src/components/Card/Card.js
  client/src/components/Card/Card.stories.js
  client/src/components/Footer/Footer.css
  client/src/components/GroupCard/GroupCard.css
  client/src/components/GroupCard/GroupCard.js
  client/src/components/GroupCard/GroupCard.stories.js
  client/src/components/PreviousTripsCard/PreviousTripsCard.css
  client/src/components/PreviousTripsCard/PreviousTripsCard.js
  client/src/components/PreviousTripsCard/PreviousTripsCard.stories.js
  client/src/components/SignUpAd/SignUpAd.css
  client/src/components/TrendingHashtagCard/TrendingHashtagCard.css
  client/src/components/TripCard/TripCard.css
  client/src/components/UpcomingEventsCard/UpcomingEventsCard.css
  client/src/components/UpcomingTripsCard/UpcomingTripsCard.css
  client/src/components/UpcomingTripsCard/UpcomingTripsCard.js
  client/src/pages/SplashPage/SplashPage.js
Labels: atomic component, molecular component

#383 Book a trip image test PR
  client/src/components/BookATripImage/BookATripImage.js
  client/src/components/BookATripImage/BookATripImage.test.js
Labels: unit testing

#402 Card Component styling issue.
  client/src/components/Card/Card.css
Labels: bug
