Repository CotripperPlatform/CoTrip, pull requests merged in 2020-03, with the labels that each got.

#417 Escalation templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: stand alone

#411 Card Component Quick Fix
  client/src/App.css
  client/src/components/Card/Card.css
  client/src/components/Card/Card.stories.js
Labels: bug

#418 added location models to models, views, serializers, urls
  Pipfile
  Pipfile.lock
  api/cotrip_app/migrations/0002_location.py
  api/cotrip_app/models.py
  api/cotrip_app/serializers.py
  api/cotrip_app/urls.py
  api/cotrip_app/views.py
  package-lock.json
Labels: backend

#444 Organize storybook components
  client/src/components/ActivityList/ActivityList.stories.js
  client/src/components/Banner/Banner.stories.js
  client/src/components/BannerImageCard/BannerImageCard.stories.js
  client/src/components/Bio/Bio.stories.js
  client/src/components/BookATripImage/BookATripImage.stories.js
  client/src/components/BookTripCard/BookTripCard.stories.js
  client/src/components/Burger/Burger.stories.js
  client/src/components/Button/Button.stories.js
  client/src/components/Card/Card.stories.js
  client/src/components/CarouselDots/CarouselDots.stories.js
  client/src/components/CommentBody/CommentBody.stories.js
  client/src/components/Connections/Connections.stories.js
  client/src/components/ExtraUsers/ExtraUsers.stories.js
  client/src/components/FileUploadComponent/FileUpload.stories.js
  client/src/components/Footer/Footer.stories.js
  client/src/components/ForumComment/ForumComment.stories.js
  client/src/components/ForumPost/ForumPost.stories.js
  client/src/components/GroupCard/GroupCard.stories.js
  client/src/components/GroupsList/GroupsList.stories.js
  client/src/components/Icon/Icon.stories.js
  client/src/components/InputSelect/InputSelect.stories.js
  client/src/components/InputTextField/InputTextField.stories.js
  client/src/components/InteractionCard/InteractionCard.stories.js
  client/src/components/Logo/Logo.stories.js
  client/src/components/MediaCard/MediaCard.stories.js
  client/src/components/NavLink/NavLink.stories.js
  client/src/components/NavLinkDropdownMenu/NavLinkDropdownMenu.stories.js
  client/src/components/Navbar/Navbar.stories.js
  client/src/components/OnboardingPills/OnboardingPills.stories.js
  client/src/components/PersonCard/PersonCard.stories.js
  client/src/components/Pill/Pill.stories.js
  client/src/components/PostBody/PostBody.stories.js
  client/src/components/PreviousTripsCard/PreviousTripsCard.stories.js
  client/src/components/ProfilePicture/ProfilePicture.stories.js
  client/src/components/SignUpAd/SignUpAd.stories.js
  client/src/components/TrendingHashtagCard/TrendingHashtagCard.stories.js
  client/src/components/TripCard/TripCard.stories.js
  client/src/components/TripDetails/TripDetails.stories.js
  client/src/components/UpcomingEventsCard/UpcomingEventsCard.stories.js
  client/src/components/UpcomingTripsCard/UpcomingTripsCard.stories.js
  client/src/pages/BookATripPage/BookATripPage.stories.js
  client/src/pages/ComingSoonPage/ComingSoonPage.stories.js
  client/src/pages/Hawaii2020/Hawaii2020.stories.js
  client/src/pages/MemberProfilePage/MemberProfilePage.stories.js
  client/src/pages/SplashPage/SplashPage.stories.js
Labels: documentation

#301 Comment body component PR
  client/src/components/Comment/Comment.css
  client/src/components/Comment/Comment.js
  client/src/components/Comment/Comment.stories.js
  client/src/components/Comment/Comment.test.js
  client/src/components/CommentBody/CommentBody.css
  client/src/components/CommentBody/CommentBody.js
Labels: bug, responsive
