Repository CotripperPlatform/CoTrip, pull requests merged in 2020-04, with the labels that each got.

#492 Api community app
  api/accounts/models.py
  api/api/settings.py
  api/community/__init__.py
  api/community/admin.py
  api/community/apps.py
  api/community/migrations/0001_initial.py
  api/community/migrations/0002_auto_20200403_0339.py
  api/community/migrations/0003_auto_20200403_0341.py
  api/community/migrations/0004_auto_20200403_2012.py
  api/community/migrations/__init__.py
  api/community/models.py
  api/community/tests.py
  api/community/views.py
  api/cotrip_app/admin.py
  api/cotrip_app/models.py
Labels: backend

#467 Updated storybook readme
  client/README.md
  client/src/assets/images/StorybookLayout.png
Labels: documentation

#490 Component discover connections
  client/src/components/PersonCardDiscover/PersonCardDiscover.css
  client/src/components/PersonCardDiscover/PersonCardDiscover.js
  client/src/components/PersonCardDiscover/PersonCardDiscover.stories.js
  client/src/components/PersonCardDiscover/PersonCardDiscover.test.js
Labels: atomic component

#415 Discover Groups component
  client/src/components/Card/Card.css
  client/src/components/Card/Card.stories.js
  client/src/components/PersonCard/PersonCard.css
Labels: atomic component

#536 Fix profile picture url bug
  api/accounts/migrations/0005_auto_20200409_1241.py
  api/accounts/models.py
  client/src/pages/HomePage/HomePage.js
Labels: bug

#538 Trip Fixtures - Resolves #526
  api/accounts/fixtures-accounts.json
  api/trip/fixtures-trip.json
Labels: Models, backend

#527 Changes to Account App - social media models and changes to profile model
  api/accounts/migrations/0005_auto_20200407_2006.py
  api/accounts/migrations/0006_auto_20200407_2139.py
  api/accounts/migrations/0007_auto_20200408_1809.py
  api/accounts/models.py
  api/accounts/serializers.py
  api/accounts/urls.py
  api/accounts/views.py
  api/community/migrations/0006_media_author.py
  api/community/models.py
  api/trip/fixtures-trip.json
  api/trip/migrations/0006_remove_location_people.py
  api/trip/models.py
Labels: Account, backend
